# Generated by Django 5.0.6 on 2024-09-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=100, null=True)),
                ('phone_number', models.PositiveIntegerField(default=0, null=True)),
                ('email_address', models.CharField(max_length=255, null=True)),
                ('box_number', models.CharField(max_length=100)),
                ('emmergency_phone_number', models.PositiveIntegerField(default=0, null=True)),
                ('passport_number', models.PositiveIntegerField(default=0, null=True)),
                ('visa_document', models.TextField(null=True)),
                ('departure_city', models.CharField(max_length=255, null=True)),
                ('destination_city', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
